"""Akribes SDK for Python — async client for the Akribes workflow server.

Quick start::

    import asyncio, os
    from akribes_sdk import AkribesClient

    async def main():
        async with AkribesClient(
            "https://akribes.example.com",
            token=os.environ["AKRIBES_TOKEN"],
        ) as client:
            proj = client.project(2)
            output = await proj.script("summarize").run_and_await(brief="…")
            print(output.execution_id, output.result)

    asyncio.run(main())

Event stream layering
---------------------
Three progressively richer APIs sit on top of the same SSE connection:

1. Layer 1 — :class:`EngineEvent` (raw ``{type, payload}``): escape hatch
   for anything the typed layer doesn't model.
2. Layer 2 — :class:`WorkflowEvent`: frozen-dataclass discriminated union
   matched on ``evt.kind`` (a ``Literal`` tag), with an :class:`Other`
   catch-all. Use :func:`to_workflow_event` for ad-hoc conversion.
3. Layer 3 — :class:`RunStream` from
   :meth:`Executions.run_stream`: async-iterable handle that also exposes
   ``await .output()``, ``.execution_id``, and ``.on.<category>(cb)``
   callback registration.
"""

from akribes_sdk._handles import ProjectHandle, ScriptHandle
from akribes_sdk._pagination import AsyncPage
from akribes_sdk._retry import ExponentialBackoff, RetryPolicy
from akribes_sdk.client import AkribesClient
from akribes_sdk.ingest_handle import IngestHandle, IngestEvent
from akribes_sdk.script_type import ScriptType
from akribes_sdk.errors import (
    AkribesConnectionError,
    AkribesConversionError,
    AkribesError,
    AkribesHTTPError,
    AkribesTimeoutError,
    AuthError,
    CaseFieldError,
    CaseTypeMismatchError,
    DocumentConversionError,
    IngestProtocolError,
    IngestTimeoutError,
    BadGateway502,
    GatewayTimeout504,
    JudgeContractError,
    NotFoundError,
    RateLimitError,
    ScriptError,
    ScriptInputMismatchError,
    ScriptSchemaChangedError,
    ServerError500,
    ServiceUnavailable503,
    TransientError,
)
from akribes_sdk.resources.documents import (
    DEFAULT_INGEST_POLL_TIMEOUT_MS,
    DocumentsClient,
    ingest_poll_timeout_ms_from_env,
)
from akribes_sdk.resources.me import Me
from akribes_sdk.models import (
    AdhocRunResult,
    AgentOutputEvent,
    AgentUnableTrigger,
    Bench,
    BenchCase,
    BenchEvent,
    BenchResult,
    BenchRun,
    BenchRunTagSessionResponse,
    BreakingInterest,
    ClaimHit,
    CompareAggregate,
    CompareCase,
    CompareReport,
    DriftedCase,
    DriftReport,
    ProjectBenchSummary,
    ClaimMiss,
    ClaimResult,
    ClientInfo,
    ContextCompactedEvent,
    ContextOverflowEvent,
    ContractWarning,
    ConversionStatus,
    ConvertResult,
    CostAggregation,
    CostByChannel,
    CostByScript,
    CostByVersion,
    DagPositionTrigger,
    Draft,
    EngineEvent,
    EngineEventType,
    IngestPhase,
    IngestProgress,
    ErrorKind,
    ExecutionChildSummary,
    ExecutionEvents,
    ExecutionOutput,
    ExecutionStatus,
    ExecutionStatusValue,
    ExecutionTaskSummary,
    ExecutionTasksResponse,
    DocumentMeta,
    GraphEdge,
    GraphNode,
    GraphResponse,
    ScriptGraph,
    HubEvent,
    InputField,
    LatestVersion,
    LogEvent,
    McpDriftResult,
    McpHealth,
    McpRefreshResult,
    McpServerSummary,
    McpToolSummary,
    Project,
    ProjectScope,
    ProjectCost,
    PublishDryRunResult,
    PutDraftResponse,
    ReconvertResult,
    RunResult,
    ScriptCost,
    RuntimeEndEvent,
    RuntimeErrorEvent,
    RuntimeStartEvent,
    RuntimeStderrEvent,
    RuntimeStdoutEvent,
    S3CredentialsRef,
    S3DocumentRef,
    S3PresignedRef,
    SandboxInfo,
    Script,
    ScriptChannel,
    ScriptVersion,
    UploadResult,
    SuspendedEvent,
    SuspendTrigger,
    TaskEndEvent,
    TaskStartEvent,
    TokenInfo,
    TokenMinted,
    TokenRole,
    TokenScopes,
    TokenUsage,
    ToolApprovalPendingEvent,
    TypedEngineEvent,
    TypeRef,
    UnableCategoryValue,
    UnableRecord,
    UnknownEvent,
    UnknownTrigger,
    ValidationErrorWire,
    ValidationExhaustedTrigger,
    ValidationFailureEvent,
    WorkflowEndEvent,
    WorkflowStartEvent,
    parse_engine_event,
    parse_suspend_trigger,
)
from akribes_sdk.run_stream import RunStream, RunStreamCallbacks
from akribes_sdk.workflow_events import (
    AgentChunk,
    Breakpoint,
    Checkpoint,
    End,
    EventCategory,
    Other,
    RuntimeEnd,
    RuntimeError,
    RuntimeStart,
    RuntimeStatus,
    RuntimeStderr,
    RuntimeStdout,
    WorkflowTotals,
    RuntimeStep,
    RuntimeWorkflowEvent,
    Start,
    TaskEnd,
    TaskStart,
    ToolApproval,
    ToolCallEnd,
    ToolCallStart,
    ValidationFailure,
    WorkflowError,
    WorkflowErrorKind,
    WorkflowEvent,
    category_of,
    reduce_runtime_events,
    reduce_runtime_events_async,
    to_workflow_event,
)
# Re-export the per-variant `ErrorEvent` class from the legacy typed-engine-event
# layer in `models`. The new typed `WorkflowEvent::Error` variant lives at
# `WorkflowError` to avoid the name clash.
from akribes_sdk.models import ErrorEvent

__version__ = "0.21.0"

__all__ = [
    "__version__",
    # Client + handles
    "AkribesClient",
    "AsyncPage",
    "IngestHandle",
    "IngestEvent",
    "ProjectHandle",
    "ScriptHandle",
    "ScriptType",
    # Retry policy
    "RetryPolicy",
    "ExponentialBackoff",
    # Errors
    "AkribesError",
    "AkribesConnectionError",
    "AkribesHTTPError",
    "AuthError",
    "NotFoundError",
    "RateLimitError",
    "TransientError",
    "ServerError500",
    "BadGateway502",
    "ServiceUnavailable503",
    "GatewayTimeout504",
    "ScriptError",
    "AkribesTimeoutError",
    "AkribesConversionError",
    "DocumentConversionError",
    "IngestProtocolError",
    "IngestTimeoutError",
    "ScriptSchemaChangedError",
    "ScriptInputMismatchError",
    "CaseFieldError",
    "CaseTypeMismatchError",
    "JudgeContractError",
    # Models
    "AdhocRunResult",
    "Bench",
    "BenchCase",
    "BenchEvent",
    "BenchResult",
    "BenchRun",
    "BenchRunTagSessionResponse",
    "CompareAggregate",
    "CompareCase",
    "CompareReport",
    "DriftedCase",
    "DriftReport",
    "ProjectBenchSummary",
    "BreakingInterest",
    "ClaimHit",
    "ClaimMiss",
    "ClaimResult",
    "ClientInfo",
    "ContractWarning",
    "ContextCompactedEvent",
    "ContextOverflowEvent",
    "ConversionStatus",
    "CostAggregation",
    "CostByChannel",
    "CostByScript",
    "CostByVersion",
    "ConvertResult",
    "Draft",
    "EngineEvent",
    "EngineEventType",
    "ErrorEvent",
    "ErrorKind",
    "ExecutionEvents",
    "ExecutionOutput",
    "ExecutionChildSummary",
    "ExecutionTaskSummary",
    "ExecutionTasksResponse",
    "DocumentMeta",
    "ExecutionStatus",
    "ExecutionStatusValue",
    "GraphEdge",
    "GraphNode",
    "GraphResponse",
    "ScriptGraph",
    "HubEvent",
    "IngestPhase",
    "IngestProgress",
    "InputField",
    "LatestVersion",
    "McpDriftResult",
    "McpHealth",
    "McpRefreshResult",
    "McpServerSummary",
    "McpToolSummary",
    "Project",
    "ProjectScope",
    "ProjectCost",
    "PublishDryRunResult",
    "PutDraftResponse",
    "ReconvertResult",
    "RunResult",
    "ScriptCost",
    "S3CredentialsRef",
    "S3DocumentRef",
    "S3PresignedRef",
    "SandboxInfo",
    "Script",
    "ScriptChannel",
    "ScriptVersion",
    "TokenInfo",
    "UploadResult",
    # Documents resource
    "DEFAULT_INGEST_POLL_TIMEOUT_MS",
    "DocumentsClient",
    "Me",
    "ingest_poll_timeout_ms_from_env",
    "TokenMinted",
    "TokenRole",
    "TokenScopes",
    "TokenUsage",
    "TypeRef",
    # SuspendTrigger + UnableRecord (Wave 4 — EPA S4 + S6)
    "AgentUnableTrigger",
    "DagPositionTrigger",
    "SuspendTrigger",
    "UnableCategoryValue",
    "UnableRecord",
    "UnknownTrigger",
    "ValidationErrorWire",
    "ValidationExhaustedTrigger",
    "parse_suspend_trigger",
    # Legacy per-variant event classes (still exported for back-compat)
    "AgentOutputEvent",
    "LogEvent",
    "RuntimeEndEvent",
    "RuntimeErrorEvent",
    "RuntimeStartEvent",
    "RuntimeStderrEvent",
    "RuntimeStdoutEvent",
    "SuspendedEvent",
    "TaskEndEvent",
    "TaskStartEvent",
    "ToolApprovalPendingEvent",
    "TypedEngineEvent",
    "UnknownEvent",
    "ValidationFailureEvent",
    "WorkflowEndEvent",
    "WorkflowStartEvent",
    "parse_engine_event",
    # Typed WorkflowEvent (Layer 2)
    "AgentChunk",
    "Breakpoint",
    "Checkpoint",
    "End",
    "WorkflowTotals",
    "EventCategory",
    "Other",
    "RuntimeEnd",
    "RuntimeError",
    "RuntimeStart",
    "RuntimeStatus",
    "RuntimeStderr",
    "RuntimeStdout",
    "RuntimeStep",
    "RuntimeWorkflowEvent",
    "Start",
    "TaskEnd",
    "TaskStart",
    "ToolApproval",
    "ToolCallEnd",
    "ToolCallStart",
    "ValidationFailure",
    "WorkflowError",
    "WorkflowErrorKind",
    "WorkflowEvent",
    "category_of",
    "reduce_runtime_events",
    "reduce_runtime_events_async",
    "to_workflow_event",
    # RunStream (Layer 3)
    "RunStream",
    "RunStreamCallbacks",
]
